### ISSUE TITLE
MlDonkeyFox2 highjacks links not destined to it

### ISSUE THREAD

**Issue by DmitryBurstein** [Robert904/MlDonkeyFox2#1]
When clicking on the following link "http://tvunderground.org.ru/torrent.php?tid=277202" the torrent.php file in it should send a torrent to another client associated with torrents in my system. It does so when MlDonkeyFox2 is disabled, but when it's enabled, the torrent.php file itself is being added to mldonkey downloads - without even telling me so via the usual notification. The bittorrent check-box is unchecked in the settings, and there was no such problem with the previous version of the extension.

**Comment by Robert904** [comment]
OK, now it should comply with the "bittorrent" preference, and only kick in when it is checked.

Now, for the way it submits the link when it is enabled, I think it's the right way...  This is the URL mldonkey must use to download himself the torrent file content, and the "torrent.php" is the way he transform the url into a name for the list... The browser uses an additional field to know what should actually be the filename when you download it, but I don't see a way to pass that to mldonkey...

**Comment by DmitryBurstein** [comment]
Great! Thank you for the quick fix. Now it's back to opening the browser's "Open with" dialog - the way it should be.
